USE [master]
GO

CREATE DATABASE [UpdtSession] ON  PRIMARY 
( NAME = N'UpdtSession', FILENAME = N'D:\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Updt_Session.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'MSession_log', FILENAME = N'D:\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Updt_Session_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [UpdtSession] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UpdtSession].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [UpdtSession] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [UpdtSession] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [UpdtSession] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [UpdtSession] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [UpdtSession] SET ARITHABORT OFF 
GO

ALTER DATABASE [UpdtSession] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [UpdtSession] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [UpdtSession] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [UpdtSession] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [UpdtSession] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [UpdtSession] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [UpdtSession] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [UpdtSession] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [UpdtSession] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [UpdtSession] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [UpdtSession] SET  DISABLE_BROKER 
GO

ALTER DATABASE [UpdtSession] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [UpdtSession] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [UpdtSession] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [UpdtSession] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [UpdtSession] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [UpdtSession] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [UpdtSession] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [UpdtSession] SET  READ_WRITE 
GO

ALTER DATABASE [UpdtSession] SET RECOVERY FULL 
GO

ALTER DATABASE [UpdtSession] SET  MULTI_USER 
GO

ALTER DATABASE [UpdtSession] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [UpdtSession] SET DB_CHAINING OFF 
GO

